import './globals.css'
import {Montserrat} from 'next/font/google';

const monserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Idealist',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monserrat.className}>{children}</body>
    </html>
  )
}
